import tensorflow as tf
import numpy as np
import os

def tflite_to_c_array(tflite_path, header_path="MicroGAN_weights.h"):
    """
    Extract weights and metadata from a TFLite model and generate a C header.
    """
    if not os.path.exists(tflite_path):
        raise FileNotFoundError(f"TFLite model not found at {tflite_path}")
    
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()
    
    details = interpreter.get_tensor_details()
    
    with open(header_path, "w") as f:
        f.write("// Auto-generated by MicroGAN\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        
        f.write("#define MicroGAN_LATENT_DIM 32\n")
        f.write("#define MicroGAN_OUTPUT_SIZE 32\n\n")

        for d in details:
            name = d['name'].replace("/", "_").replace(".", "_").replace(":", "_")
            index = d['index']
            try:
                tensor = interpreter.get_tensor(index)
            except ValueError:
                continue

            # Skip non-weight tensors if they are empty
            if tensor.size == 0:
                continue

            # Export quantization parameters
            quant = d.get('quantization_parameters', {})
            scales = quant.get('scales', [])
            zero_points = quant.get('zero_points', [])
            
            if len(scales) > 0:
                f.write(f"const float MicroGAN_{name}_scale = {scales[0]}f;\n")
            if len(zero_points) > 0:
                f.write(f"const int32_t MicroGAN_{name}_zp = {zero_points[0]};\n")

            # Export the tensor data
            if tensor.dtype == np.int8:
                f.write(f"const int8_t MicroGAN_{name}_data[] = {{")
                f.write(", ".join(map(str, tensor.flatten())))
                f.write("};\n")
                f.write(f"#define MicroGAN_{name}_LEN {tensor.size}\n\n")
            elif tensor.dtype == np.int32:
                f.write(f"const int32_t MicroGAN_{name}_data[] = {{")
                f.write(", ".join(map(str, tensor.flatten())))
                f.write("};\n")
                f.write(f"#define MicroGAN_{name}_LEN {tensor.size}\n\n")
            elif tensor.dtype == np.float32:
                f.write(f"const float MicroGAN_{name}_data[] = {{")
                f.write(", ".join(map(str, tensor.flatten())))
                f.write("};\n")
                f.write(f"#define MicroGAN_{name}_LEN {tensor.size}\n\n")

    print(f"Detailed C header generated at {header_path}")

if __name__ == "__main__":
    pass
